# Playbook to setup workstation and create osp network, router, SG and ssh keypair

- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation
       ansible_ssh_private_key_file: /root/.ssh/openstack.pem
       ansible_ssh_user: cloud-user

    register: debug_host

  - debug:
      var: debug_host

- hosts: workstation
  become: yes
  gather_facts: no
  tasks:
    - ping:
      register: ping

    - debug:
        var: ping

- hosts: workstation
  become: yes
  roles:
    - setup-workstation

- import_playbook: site-install-isolated-node.yml 

